#!/usr/bin/perl

use strict;
use warnings;

use LWP::UserAgent;
use JSON::XS qw(decode_json);

my $url    = "http://localhost:8080";

sub ans {
	my ($code, $msg) = @_;
	print "PASSIVE-CHECK:response_get_time;$code;$msg\n";
	exit(0);
}

my $ua  = LWP::UserAgent->new;
my $req = HTTP::Request->new("GET", "$url/debug/vars");
my $res = $ua->request($req);

if (!$res->is_success) {
	ans(2, $res->status_line);
}

my $json = eval { decode_json($res->content) };
ans(2, "Bad json")
	if $@;

ans(2, "Metric not found")
	if !$json->{Kafka}->{"main.Response.GET.Time.avg"};

my $resp_get_time_avg = int($json->{Kafka}->{"main.Response.GET.Time.avg"} / 1000000);

ans(2, "GET response to slow, $resp_get_time_avg ms")
	if $resp_get_time_avg > 10000;

ans(0, "OK");
