#!/usr/bin/perl

use strict;
use warnings;

use LWP::UserAgent;
use JSON qw(decode_json);

my $config_file = "/etc/yandex/khp/kafka.json";

sub read_config {
	my $json_text = "";
	{
		local $/;
		open(my $fh, '<', $config_file);
		$json_text = <$fh>;
		close($fh);
	}
	return JSON->new->utf8->relaxed->decode($json_text);
}

my $config = read_config();
my $url    = "http://localhost:" . $config->{khp}->{port};

sub ans {
	my ($code, $msg) = @_;
	print "PASSIVE-CHECK:replicas_number;$code;$msg\n";
	exit(0);
}

my $topics = {};
foreach my $topic (@{$config->{kafka}->{topics}}) {
	$topics->{$topic->{name}} = $topic->{partitions} * @{$config->{kafka}->{hosts}};
}

foreach my $topic (keys %{$topics}) {
	my $ua  = LWP::UserAgent->new;
	my $req = HTTP::Request->new("GET", "$url/v1/info/topics/$topic");
	my $res = $ua->request($req);

	if (!$res->is_success) {
		my $json = eval { decode_json($res->content) };
		ans(2, $res->status_line)
			if $@;

		if ($json->{status} eq "error") {
			ans(2, $json->{data});
		}

		ans(2, $res->status_line);
	}

	my $json = decode_json($res->content);
	if ($json->{status} ne "success") {
		ans(2, $json->{data});
	}

	my $sum = 0;
	foreach my $p (@{$json->{data}}) {
		$sum += $p->{replicasnum};
	}

	ans(0, "OK")
		if $sum == $topics->{$topic};

	ans(2, "Topic $topic, replicas != " . $topics->{$topic});
}
