#!/usr/bin/perl

use strict;
use warnings;

use LWP::UserAgent;
use JSON qw(decode_json);

my $config_file = "/etc/yandex/khp/kafka.json";

sub read_config {
	my $json_text = "";
	{
		local $/;
		open(my $fh, '<', $config_file);
		$json_text = <$fh>;
		close($fh);
	}
	return JSON->new->utf8->relaxed->decode($json_text);
}

my $config = read_config();
my $url    = "http://localhost:" . $config->{khp}->{port};

my @bad_codes = qw(500 502 503);

sub ans {
	my ($code, $msg) = @_;
	print "PASSIVE-CHECK:response_error_codes;$code;$msg\n";
	exit(0);
}

my $ua  = LWP::UserAgent->new;
my $req = HTTP::Request->new("GET", "$url/debug/vars");
my $res = $ua->request($req);

if (!$res->is_success) {
	ans(2, $res->status_line);
}

my $json = eval { decode_json($res->content) };
ans(2, "Bad json")
	if $@;

foreach my $code (@bad_codes) {
	ans(2, "Status $code == " . $json->{Kafka}->{HTTPStatus}->{$code})
		if $json->{Kafka}->{HTTPStatus}->{$code} > 0;
}

ans(0, "OK");
