#!/bin/sh
# preinst script for mon-kafka-http-proxy
#
# see: dh_installdeb(1)

set -e

remove_obsolete_configs() {
	for f in /etc/monrun/conf.d/khp-* /etc/snaked/jobs/graphite-khp-*; do
		[ ! -e "$f" ] ||
			rm -rf -- "$f" ||:
	done
}

case "$1" in
	upgrade)
		if dpkg --compare-versions "${2:-0.4.6}" le 0.4.5; then
			remove_obsolete_configs
		fi
		;;
esac

exit 0
